# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'da4e061f-4564-48a8-9b25-832b7eef7253'
  imageRepository: 'doccomparison'
  containerRegistry: 'ydigital.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'stable'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Lint
  jobs:
  - job: LintJob
    displayName: LintJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        wget https://github.com/Y-Digital/code-quality/raw/main/.flake8 &&
        wget https://github.com/Y-Digital/code-quality/raw/main/requirements-dev.txt &&
        python -m pip install -r requirements-dev.txt &&
        flake8 --config .flake8 . &&
        flake8 --select BLK100 .
      displayName: "Flake8 linting and checking Black style"
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
